language:
  - rust
  - node_js

sudo: false

cache: 
  - cargo
  - yarn

before_install:
  - yarn install wasm-pack-plugin -G

jobs:
  script:
    - yarn build
  
deploy:
  provider: s3
  bucket: life.jonstites.com  
  skip_cleanup: true
  local_dir: dist
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY
  region: $AWS_DEFAULT_REGION
  cache_control: "max-age=31536000"
  detect_encoding: true
  on:
    branch:
      - master
      - feature/bit_and_growable_hash
    
notifications:
  email:
    on_success: never