dist: bionic

language: rust

before_install:
  - curl -O https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-x64.tar.xz
  - sudo mkdir -p nodejs
  - sudo tar xvJf node-v12.16.2-linux-x64.tar.xz -C nodejs
  - export PATH="nodejs/node-v12.16.2-linux-x64/bin:$PATH"
  - node --version
  - npm install -g npm@latest
  - yarn install
  - node --version
  - yarn global add wasm-pack  
  - wasm-pack --version
  - webpack --version
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH="$HOME/.yarn/bin:$PATH"

jobs:
  script:
    - cargo test
    - yarn build
  
deploy:
  provider: s3
  bucket: life.jonstites.com  
  skip_cleanup: true
  local_dir: dist
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY
  region: $AWS_DEFAULT_REGION
  cache_control: "max-age=31536000"
  detect_encoding: true
  on:
    branch:
      - master
      - feature/bit_and_growable_hash
    
notifications:
  email:
    on_success: never