language:
  - rust
  - node_js

sudo: false

cache: cargo

before_install:
  - npm install -g npm@latest
  
matrix:
  include:

  # Builds with wasm-pack.
  - rust: beta
    env: RUST_BACKTRACE=1
    addons:
      firefox: latest
      chrome: stable
    before_script:
      - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
      - (test -x $HOME/.cargo/bin/cargo-generate || cargo install --vers "^0.2" cargo-generate)
      - cargo install-update -a
      - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
    script:
      - cargo generate --branch $TRAVIS_BRANCH --git . --name testing
      # Having a broken Cargo.toml (in that it has curlies in fields) anywhere
      # in any of our parent dirs is problematic.
      - mv Cargo.toml Cargo.toml.tmpl
      - cd testing
      - wasm-pack build
      - wasm-pack test --chrome --firefox --headless

before_deploy:
  - wasm-pack build
  - wasm-pack test --chrome --firefox --headless
  - cd pkg
  - npm link
  - cd ../www
  - npm install
  - npm link game-of-life
  - npm run build
  - cd ..
  
deploy:
  provider: s3
  edge:
    source: jonstites/dpl
    branch: feature/mime-types-3
  bucket: life.jonstites.com  
  skip_cleanup: true
  local_dir: www/dist
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY
  region: $AWS_DEFAULT_REGION
  cache_control: "max-age=31536000"
  detect_encoding: true
  on:
    branch:
      - master
      - deploy-test3
    
notifications:
  email:
    on_success: never
